[build]
    command = "npm run build"

[[headers]]
    # Define which paths this specific [[headers]] block will cover.
    for = "/*"
    [headers.values]
        # Force HTTPS only.
        Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
        # Load scripts only via HTTPS and from allowed domains.
        Content-Security-Policy = """
            default-src 'self';
            img-src 'self' res.cloudinary.com; 
            style-src 'self' 'unsafe-inline'; 
            script-src 'self' 'unsafe-inline'; 
            connect-src 'self' paregisme.herokuapp.com; 
            base-uri 'self'; 
            form-action 'self';
            object-src 'none';
            frame-ancestors 'none';
        """
        # Add reflective XSS protection.
        X-XSS-Protection = "1; mode=block"
        # We don't use iframes. Block them.
        X-Frame-Options = "DENY"
        # Don't allow Mime-sniffing.
        X-Content-Type-Options = "nosniff"
        # Don't use referrer.
        Referrer-Policy = "no-referrer"